[package]
name = "commonmeta"
version = "0.1.0"
edition = "2021"
authors = ["Front Matter <info@front-matter.io>"]
description = "CommonMeta tools for metadata conversion"
license = "MIT"
readme = "README.md"

[[bin]]
name = "commonmeta"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
clap = "4.0"
rand = "0.8"
regex = "1.9"
base32 = "0.4"
lazy_static = "1.5.0"
serde = "1.0.219"
url = "2.5.4"
serde_json = "1.0.140"
zip = "2.6.1"
thiserror = "2.0.12"
chrono = { version = "0.4.40", features = ["clock"] }
avro-rs = "0.13.0"
serde_yaml = "0.9.34"
csv = "1.3.1"
